# Usa un'immagine base di Node.js
FROM node:18 AS build

# Imposta la cartella di lavoro all'interno del container
WORKDIR /app

# Copia il file package.json e package-lock.json nella cartella di lavoro
COPY frontend/package*.json ./

# Installa le dipendenze
RUN npm install

# Copia tutti i file del frontend nel container
COPY frontend/ ./

# Costruisci l'applicazione Next.js
RUN npm run build

# Espone la porta su cui Next.js verrà eseguito (3000 è la porta predefinita)
EXPOSE 3000

# Comando per avviare il server di Next.js
CMD ["npm", "run", "start"]
