version: '3'

services:
  frontend:
    image: goose-authorization-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - frontend/.env.local
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: goose-authorization-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - frontend/.env.local
    networks:
      - app-network
    volumes:
      - ./backend:/backend  # Assicurati che il percorso sulla macchina host sia corretto

networks:
  app-network:
    driver: bridge
