version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"       # Esponi la porta del backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"       # Porta del frontend
    environment:
      - REACT_APP_API_URL=http://backend:5001 # Variabile d'ambiente per comunicare con il backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
