version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local  # Carica variabili da .env nella cartella frontend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - frontend/.env.local  # Modifica per caricare variabili dal file .env del backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
