version: '3'

services:
  frontend:
    image: goose-authorization-frontend
    build:
      context: ./frontend  # Cartella contenente il frontend
      dockerfile: dockerfile  # Assicurati che il nome del Dockerfile sia corretto
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local  # Carica variabili di ambiente per il frontend
    networks:
      - app-network
    depends_on:
      - backend  # Assicurati che il frontend aspetti che il backend sia pronto

  backend:
    image: goose-authorization-backend
    build:
      context: ./backend  # Cartella contenente il backend
      dockerfile: dockerfile  # Assicurati che il nome del Dockerfile sia corretto
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - frontend/.env.local  # Carica variabili di ambiente specifiche del backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

