# Usa un'immagine base di Python
FROM python:3.12-slim

# Imposta la cartella di lavoro all'interno del container
WORKDIR /backend

# Imposta variabili di ambiente per Python per unbuffered logging
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Copia il file requirements.txt dalla cartella backend al container
COPY requirements.txt /backend/requirements.txt

# Installa le dipendenze da requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia i certificati SSL
COPY ./certs /backend/certs

# Copia tutti i file del backend nel container
COPY ./ /backend/

# Esponi la porta sulla quale Flask ascolterà (5001)
EXPOSE 5001

# Imposta le variabili di ambiente per Flask
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Comando per eseguire l'applicazione Flask
CMD ["python", "-u", "app.py"]