# Usa un'immagine base di Python
FROM python:3.12-slim

# Imposta la cartella di lavoro nel container
WORKDIR /app

# Copia i file del progetto
COPY . /app

# Installa le dipendenze
RUN pip install -r requirements.txt

#esponi la porta
EXPOSE 5001

# Comando per eseguire il server del backend (modifica a seconda del framework che usi, ad esempio Flask o FastAPI)
CMD ["python", "app.py"]
