apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cla01/frontend-image:latest  # Sostituisci con l'immagine del tuo frontend
          ports:
            - containerPort: 3001  # Modifica se il tuo frontend usa una porta diversa
          env:
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-local-config
                  key: NEXT_PUBLIC_SUPABASE_URL  # Usa la chiave corretta dal ConfigMap
            - name: SUPABASE_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-local-config
                  key: NEXT_PUBLIC_SUPABASE_ANON_KEY  # Usa la chiave corretta dal ConfigMap
          resources:
            requests:
              memory: "512Mi"  # Memoria minima richiesta
              cpu: "500m"      # CPU minima richiesta
            limits:
              memory: "1Gi"    # Limite massimo di memoria
              cpu: "1000m"     # Limite massimo di CPU
